openapi: 3.0.3
info:
  title: AI Chat API
  description: API for AI-powered chat interface with voice input support
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.yourdomain.com
    description: Production server

paths:
  /api/{user_id}/chat:
    post:
      summary: Send message to AI assistant
      description: Process user message through AI assistant with optional voice input
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the authenticated user
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message to the AI assistant
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: integer
                  description: Optional existing conversation ID
                  example: 123
              required:
                - message
      responses:
        '200':
          description: Successful response from AI assistant
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: integer
                    description: The conversation ID (newly created or existing)
                  response:
                    type: string
                    description: The AI assistant's response
                    example: "I've added 'Buy groceries' to your task list."
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the tool called
                        arguments:
                          type: object
                          description: Arguments passed to the tool
                        result:
                          type: object
                          description: Result from the tool call
                required:
                  - conversation_id
                  - response
                  - tool_calls
        '400':
          description: Bad request - invalid input
        '401':
          description: Unauthorized - invalid or missing authentication
        '403':
          description: Forbidden - user does not have access to this resource
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ChatMessage:
      type: object
      properties:
        id:
          type: integer
          description: Unique message identifier
        conversation_id:
          type: integer
          description: Associated conversation
        role:
          type: string
          enum: [user, assistant]
          description: Who sent the message
        content:
          type: string
          description: The message content
        created_at:
          type: string
          format: date-time
          description: Timestamp of creation
      required:
        - id
        - conversation_id
        - role
        - content
        - created_at

security:
  - BearerAuth: []