apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  # Use Kubernetes secrets in production
  - name: vaultName
    value: "todo-secrets"
  # For local development, use local secret store
  # type: secretstores.local.file
  # metadata:
  # - name: secretsFile
  #   value: "./secrets.json"
scopes:
- todo-backend
- notification-service
- recurring-service
---
# Local development secret store configuration
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secretstore
  namespace: default
spec:
  type: secretstores.local.env
  version: v1
  metadata: []
scopes:
- todo-backend
